name: Publish game
run-name: Publish game 🚀
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: npm run build